on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
jobs:
  scan_job:
    name: Boost Security Scanner
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
    - name: Login to ECR
      uses: docker/login-action@v1
      with:
          registry: 706352083976.dkr.ecr.us-east-2.amazonaws.com
    - name: BoostSecurity Scanner
      uses: peaudecastor/boost-security-scanner-github@master-v2
      with:
          action: scan
          additional_args: --partial
          api_token: ${{ secrets.BOOST_API_TOKEN }}
  brakeman_job:
    name: Brakeman Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Brakeman Scanner
        uses: peaudecastor/boost-security-scanner-github@master-v2
        with:
          action: exec
          additional_args: --partial --force --log-level=DEBUG --log-level=boost.subprocess.out=DEBUG
          api_token: ${{ secrets.BOOST_API_TOKEN }}
          exec_command: "docker run -v %CWD%:/code presidentbeef/brakeman --format sarif" # an example of using docker to run a SARIF command
  complete_scan:
    name: Complete Scan
    needs: [scan_job, brakeman_job]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Complete Scan
        uses: peaudecastor/boost-security-scanner-github@master-v2
        with:
          action: complete
          api_token: ${{ secrets.BOOST_API_TOKEN }}
